ALTER TABLE villages
    ADD COLUMN IF NOT EXISTS rt_hamlet_one BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS rt_hamlet_two BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS rw_hamlet_one BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS rw_hamlet_two BIGINT NOT NULL DEFAULT 0;
