name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run Tests
        run: go test -v ./...

      - name: Build Binary
        run: GOOS=linux GOARCH=amd64 go build -o main ./cmd/api

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cipicung-be-binary
          path: main
          retention-days: 1

  deploy:
    name: Deploy to VPS
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: cipicung-be-binary

      - name: Transfer Binary to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          source: "main"
          target: "/home/ilham/app/desa-cipicung-be/"

      - name: Restart Service on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/ilham/app/desa-cipicung-be/
            chmod +x main
            echo "${{ secrets.VPS_PASSWORD }}" | sudo -S systemctl restart cipicung-api.service
