name: CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run Tests
        run: go test -v ./...

      - name: Build Binary
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 \
          go build -o main ./cmd/api

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cipicung-be-binary
          path: main
          retention-days: 1

  deploy:
    name: Deploy to VPS
    needs: build

    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: cipicung-be-binary
          path: artifact

      - name: Transfer Binary
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}

          key: ${{ secrets.VPS_SSH_KEY }}

          source: "artifact/main"
          target: "/home/ilham/app/desa-cipicung-be/"
          strip_components: 1
          overwrite: true

      - name: Prepare Binary
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}

          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            set -e

            cd /home/ilham/app/desa-cipicung-be

            chmod +x main

            echo "Deployment berhasil"
            whoami
            pwd
            ls -lah main
