name: CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run Tests
        run: go test -v ./...

      - name: Build Binary
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 \
          go build -o main.new ./cmd/api

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cipicung-be-binary
          path: main.new
          retention-days: 1

  deploy:
    name: Deploy to VPS
    needs: build

    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    runs-on: ubuntu-latest
    env:
      APP_DIR: /home/ilham/app/desa-cipicung-be
      APP_SERVICE: desa-cipicung-be

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: cipicung-be-binary
          path: artifact

      - name: Stop App
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}

          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            set -e

            APP_DIR="${{ env.APP_DIR }}"
            APP_SERVICE="${{ env.APP_SERVICE }}"

            if systemctl cat "${APP_SERVICE}" >/dev/null 2>&1; then
              sudo systemctl stop "${APP_SERVICE}" || true
            else
              pkill -f "${APP_DIR}/main" || true
            fi

      - name: Transfer Binary
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}

          key: ${{ secrets.VPS_SSH_KEY }}

          source: "artifact/main.new"
          target: "${{ env.APP_DIR }}/"
          strip_components: 1
          overwrite: true

      - name: Prepare Binary
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}

          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            set -e

            APP_DIR="${{ env.APP_DIR }}"
            APP_SERVICE="${{ env.APP_SERVICE }}"

            cd "${APP_DIR}"

            mv main.new main
            chmod +x main

            if systemctl cat "${APP_SERVICE}" >/dev/null 2>&1; then
              sudo systemctl start "${APP_SERVICE}"
            else
              nohup "${APP_DIR}/main" > "${APP_DIR}/app.log" 2>&1 &
            fi

            echo "Deployment berhasil"
            whoami
            pwd
            ls -lah main
